/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.airline_reservation_system;

import static java.awt.SystemColor.desktop;


/**
 *
 * @author ajees
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
//    boolean islogin = false;
    public MainWindow() {
        initComponents();
        LoginWindow login = new LoginWindow();
        jDesktopPane1.add(login);
        login.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        customer = new javax.swing.JMenu();
        addnewcustomer = new javax.swing.JMenuItem();
        search = new javax.swing.JMenuItem();
        Book_tickets = new javax.swing.JMenu();
        Ticket = new javax.swing.JMenuItem();
        add_flight = new javax.swing.JMenuItem();
        report = new javax.swing.JMenuItem();
        user = new javax.swing.JMenu();
        create_user = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1500, 900));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1500, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );

        customer.setText("Customer");
        customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerActionPerformed(evt);
            }
        });

        addnewcustomer.setText("Add customer");
        addnewcustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addnewcustomerActionPerformed(evt);
            }
        });
        customer.add(addnewcustomer);

        search.setText("Search customer");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        customer.add(search);

        jMenuBar1.add(customer);

        Book_tickets.setText("Ticket");
        Book_tickets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Book_ticketsActionPerformed(evt);
            }
        });

        Ticket.setText("Ticket");
        Ticket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TicketActionPerformed(evt);
            }
        });
        Book_tickets.add(Ticket);

        add_flight.setText("Add flight");
        add_flight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_flightActionPerformed(evt);
            }
        });
        Book_tickets.add(add_flight);

        report.setText("Report");
        report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportActionPerformed(evt);
            }
        });
        Book_tickets.add(report);

        jMenuBar1.add(Book_tickets);

        user.setText("User");

        create_user.setText("Create user");
        create_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create_userActionPerformed(evt);
            }
        });
        user.add(create_user);

        jMenuBar1.add(user);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerActionPerformed
        // TODO add your handling code here
    }//GEN-LAST:event_customerActionPerformed

    private void add_flightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_flightActionPerformed
        // TODO add your handling code here:
        Add_flight addflight = new Add_flight();
        jDesktopPane1.add(addflight);
        addflight.setVisible(true);
    }//GEN-LAST:event_add_flightActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        Search_customer search = new Search_customer();
        jDesktopPane1.add(search);
        search.setVisible(true);
    }//GEN-LAST:event_searchActionPerformed

    private void Book_ticketsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Book_ticketsActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_Book_ticketsActionPerformed

    private void TicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TicketActionPerformed
        // TODO add your handling code here:
        Ticket ticket = new Ticket();
        jDesktopPane1.add(ticket);
        ticket.setVisible(true);
    }//GEN-LAST:event_TicketActionPerformed

    private void reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportActionPerformed
        // TODO add your handling code here:
        Report report = new Report();
        jDesktopPane1.add(report);
        report.setVisible(true);
    }//GEN-LAST:event_reportActionPerformed

    private void create_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_userActionPerformed
        // TODO add your handling code here:
        Create_user createuser = new Create_user();
        jDesktopPane1.add(createuser);
        createuser.setVisible(true);
    }//GEN-LAST:event_create_userActionPerformed

    private void addnewcustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addnewcustomerActionPerformed
        // TODO add your handling code here:
        Add_customer addcustomer = new Add_customer();
        jDesktopPane1.add(addcustomer);
        addcustomer.setVisible(true);
    }//GEN-LAST:event_addnewcustomerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Book_tickets;
    private javax.swing.JMenuItem Ticket;
    private javax.swing.JMenuItem add_flight;
    private javax.swing.JMenuItem addnewcustomer;
    private javax.swing.JMenuItem create_user;
    private javax.swing.JMenu customer;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem report;
    private javax.swing.JMenuItem search;
    private javax.swing.JMenu user;
    // End of variables declaration//GEN-END:variables
}
